### ISSUE TITLE
mt4 docker virtualization consulting

### ISSUE THREAD

**Issue by happysalada** [EA31337/EA-Tester#143]
Hey,

   I'm Raphael, I run a small financial company using mt4. At the moment we need help on a project around mt4 virtualization with docker. I'm wondering if you have time to do a bit of consulting. If yes, would you tell me what your desired rate per hour would be?

   If you're interested, you can contact me at raphael at forunion.com
   
   If you're not, feel free to close the issue, no worries.

Let me know if you need any more information,
Raphael

**Comment by kenorb** [comment]
Thank you for the contact, I've sent the e-mail.
