### ISSUE TITLE
ERROR: TestExpert file (MACD) not found!

### ISSUE THREAD

**Issue by magick93** [EA31337/EA-Tester#211]
When I run `docker run ea31337/ea-tester run_backtest -e MACD -y 2019 -v -t` it fails with `ERROR: TestExpert file (MACD) not found!`.

# Full output

```
Loading /opt/scripts/.aliases.inc.sh... 
Loading /opt/scripts/.funcs.inc.sh... 
Loading /opt/scripts/.funcs.cmds.inc.sh... 
Loading /opt/scripts/.funcs.sets.inc.sh... 
INFO: Checking platform...
INFO: Installed Terminal: 4.0.0.1260
INFO: Installed MetaEditor: 5.0.0.2302
Copying ini files...
'/opt/conf/mt4-tester.ini' -> '/home/ubuntu/.wine/drive_c/MetaTrader 4/config/mt4-tester.ini'
'/opt/conf/terminal.ini' -> '/home/ubuntu/.wine/drive_c/MetaTrader 4/config/terminal.ini'
INFO: Locating TestExpert file (MACD)...
ERROR: TestExpert file (MACD) not found!
ERROR: Exiting /opt/scripts/run_backtest.sh with 1
413 on_error /opt/scripts/.funcs.inc.sh
384 main /opt/scripts/run_backtest.sh
Exiting /opt/scripts/run_backtest.sh with 1
```

**Comment by kenorb** [comment]
The sample indicator files has been removed from the container.

However you can try the following command:

    docker run ea31337/ea-tester run_backtest -e TestEnvelopes -y 2019 -v -t

Or you can specify a custom EA URL, e.g.

    docker run ea31337/ea-tester run_backtest -e https://github.com/EA31337/EA31337/releases/download/v1.079/EA31337-Lite-v1.079.ex4 -v

**Comment by magick93** [comment]
Fantastic. That worked.

Thank you.
