### ISSUE TITLE
TestGenerator: unmatched data error (volume limit 2406 at 2023.02.02 14:30 exceeded)

### ISSUE THREAD

**Issue by IGOmt4** [EA31337/EA-Tester#225]
Hello everyone please help me with mt4 when i run tester for test the advisor that writed me thats writing this error in the journal 2023.02.06 23:15:00.907	TestGenerator: unmatched data error (volume limit 2406 at 2023.02.02 14:30 exceeded) and this advisor do only 2 orders please help me to solve those problems.I have puted that 4 files(indicator in what i have writed my advisor and the advisor(ex4,mq4)) in zip file.
[IGO.zip](https://github.com/EA31337/EA-Tester/files/10668455/IGO.zip)

**Comment by kenorb** [comment]
Can you paste which command are you running the tester?
Have you created your own custom backtest data?

> TestGenerator: unmatched data error (volume limit ... exceeded)

it relates to the backtesting data issues, it means the volume values aren't matching for some reason. E.g. sum of volume from lower timeframe exceeds the volume from the higher timeframe (I guess).

It's something with how you generated your backtest data. Let me know how you did it. Which script have you used?

**Comment by IGOmt4** [comment]
I am working with alpari mt4 and i click on Ctrl+R or only click the bootom Strategic tester

**Comment by IGOmt4** [comment]
> Можете ли вы вставить, какой командой вы запускаете тестер? Вы создали свои собственные данные для тестирования на истории? Поскольку у меня еще нет выпущенных на 2023 год.
> 
> > TestGenerator: несопоставленная ошибка данных (предел объема... превышен)
> 
> это относится к проблемам с данными обратного тестирования (о чем сообщает платформа MT при проверке данных), это означает, что значения объема по какой-то причине не совпадают. Например, сумма объемов на младшем таймфрейме превышает объем на старшем таймфрейме (наверное).
> 
> Это связано с тем, как вы сгенерировали данные для тестирования на истории. Дайте мне знать, как вы это сделали. Какой скрипт вы использовали?



> Can you paste which command are you running the tester? Have you created your own custom backtest data? As I don't have any for 2023 released yet.
> 
> > TestGenerator: unmatched data error (volume limit ... exceeded)
> 
> it relates to the backtesting data issues (as reported by MT platform while validating the data), it means the volume values aren't matching for some reason. E.g. sum of volume from lower timeframe exceeds the volume from the higher timeframe (I guess).
> 
> It's something with how you generated your backtest data. Let me know how you did it. Which script have you used?

I am working with alpari mt4 and i use th combination Ctrl+R or just clicking bootom - Strategic tester.The filces with script i have puted under my question.
![Screenshot_1](https://user-images.githubusercontent.com/124624992/217590244-44f22fc4-61ee-4fdb-8376-9993ed56109c.png)

**Comment by IGOmt4** [comment]
> Can you paste which command are you running the tester? Have you created your own custom backtest data? As I don't have any for 2023 released yet.
> 
> > TestGenerator: unmatched data error (volume limit ... exceeded)
> 
> it relates to the backtesting data issues (as reported by MT platform while validating the data), it means the volume values aren't matching for some reason. E.g. sum of volume from lower timeframe exceeds the volume from the higher timeframe (I guess).
> 
> It's something with how you generated your backtest data. Let me know how you did it. Which script have you used?

I am using alpari mt4 and i use combination Ctrl+R or just clicking bottom startegic tester. The files with scripts(indicator that i have used for writing the advisor(TMA_Fair ex.4 mq.4) and advisor that i have writed (IGOex.4 mq.4)) i have puted under my question The files are in IGO.zip file. 
![Screenshot_1](https://user-images.githubusercontent.com/124624992/217591459-8b91cc5e-36e8-4a47-b42d-31d091546d6e.png)

**Comment by kenorb** [comment]
You've to contact MetaTrader support, as the error isn't related to this project.
This project is about backtesting using Docker, and you're using MetaTrader in a regular way.
So it's not possible to fix the error as part of this project, because I cannot reproduce it using Docker setup.

**Comment by IGOmt4** [comment]
> You've to contact MetaTrader support, as the error isn't related to this project. This project is about backtesting using Docker, and you're using MetaTrader 4 in a regular way. So it's not possible to fix the error as part of this project, because I cannot reproduce it using Docker setup.

Ok thank you.
